# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: job0
  pool: Windows_Pool

- job: job1
  dependsOn: job0
  pool: Windows_Pool

  steps:
  - script: echo job1!
    displayName: 'Run a one-line script'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        & 'start-process -FilePath "C:\Windows\System32\winver.exe" -Wait'
  # - task: PowerShell@2
  #   inputs:
  #     filePath: '$(Build.Repository.LocalPath)/build/depoy_veristand_project.ps1'
  # #    ignoreLASTEXITCODE: true
  #     runScriptInSeparateScope: false
  #     showWarnings: true

- job: job2
  dependsOn: job0
  pool: Windows_Pool

  steps:
  - script: echo job2!
    displayName: 'Run a one-line script'

  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: 'Stop-Process -Name "Veristand"'
  #     workingDirectory: '$(Build.Repository.LocalPath)'