# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:

  - stage: Build
    jobs:
    - job: Build

  - stage: Build_Stage
    dependsOn: Build
    jobs:
      - job: Build_MIL_GenericTarget
        pool: Windows_Pool
    #      vmImage: ubuntu-latest

        steps:
        - script: echo Hello, Mathworks!
        - script: echo $(Build.SourceBranch)
          displayName: 'Run a one-line script'

        - script: |
            echo Add other tasks to build, test, and deploy your project.
          displayName: 'Run a multi-line script'

        - task: BatchScript@1
          inputs:
            filename: 'C:\Users\dsamuels\dummy.bat'

      - job: Build_MIL_VeristandTarget
        # using Veristand Model Framework
        pool:
          vmImage: ubuntu-latest

        steps:
        - script: echo Hello, Veristand!
          displayName: 'Run a one-line script'

        - script: |
            echo Add other tasks to build, test, and deploy your project.
            whoami
          displayName: 'Run a multi-line script'

      - job: Build_MIL_FPGATarget
        pool: Windows_Pool

      - job: Build_MIL_EmbededTarget # DUT as target
        pool: Windows_Pool
    #      vmImage: ubuntu-latest
  - stage: Build_Stage_HIL
    dependsOn: Build
    jobs:
      - job: Mathworks_B
        pool: Windows_Pool

        steps:
        - script: echo Hello HIL, Mathworks!
          displayName: 'Run a one-line script'

      - job: Veristand_B
        pool:
          vmImage: ubuntu-latest

        steps:
        - script: echo Hello HIL, Veristand!
          displayName: 'Run a one-line script'

  - stage: Test_Stage
    dependsOn: Build_Stage
    jobs:
    - job: MIL_TEST