# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
  - job: Mathworks
    pool: Windows_Pool
#      vmImage: ubuntu-latest

    steps:
    - script: echo Hello, Mathworks!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        call winver &
      displayName: 'Run a multi-line script'

  - job: Veristand
    pool:
      vmImage: ubuntu-latest

    steps:
    - script: echo Hello, Veristand!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        whoami
      displayName: 'Run a multi-line script'

