# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: job0
  pool: Windows_Pool

- job: job1
  dependsOn: job0
  pool: Windows_Pool

  steps:
  - script: echo "job1"
    displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: 'C:\Program Files (x86)\National Instruments\VeriStand 2020\veristand-server.exe start'

  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: 'winver.exe'
  #     workingDirectory: 'C:\Windows\System32'
  #     runScriptInSeparateScope: true
  
  #     runScriptInSeparateScope: true
  # - task: PowerShell@2
  #   inputs:
  #     filePath: '$(Build.Repository.LocalPath)/build/depoy_veristand_project.ps1'
  #     runScriptInSeparateScope: true
  #    ignoreLASTEXITCODE: true
  #    runScriptInSeparateScope: false
  #    showWarnings: true

- job: job2
  dependsOn: job0
  pool: Windows_Pool

  steps:
  - script: echo job2!
    displayName: 'Run a one-line script'

  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: 'Stop-Process -Name "Veristand"'
  #     workingDirectory: '$(Build.Repository.LocalPath)'